services:
  app:
    container_name: boonkrua-backend
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT="Development"
      - INFISICAL_TOKEN=${INFISICAL_BOONKRUA_TOKEN}
    restart: always

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: boonkrua-keycloak
    command:
      - start-dev
    environment:
      KC_DB: dev-file
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "9090:8080"
    #    volumes:
    #      - ./realm-export.json:/realm-export.json 
    restart: always
